[tool.poetry]
name = "terraform-vault-backend"
version = "0.1.0"
description = "A Vault backend for Terraform implemented as an HTTP server."
authors = ["emanueljg <emanueljohnsongodin@gmail.com>"]
readme = "README.md"
packages = [ {include = "src"}]

[tool.poetry.dependencies]
python = ">= 3.8, < 3.13"
fastapi = "^0.109.1"
hvac = "^2.1.0"
uvicorn = "^0.25.0"


[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.4"
ruff = "^0.1.14"
mypy = "^1.8.0"
pytest = "^8.2.0"

[[tool.poe.include]]
path = "tests/integration/tasks.toml"
cwd = "tests/integration"

[tool.poe.tasks]
start = "python -m src"

lint = "ruff check . --fix"
lint_ro = "ruff check . --no-fix"

format = "ruff format ."
format_ro = "ruff format . --check"

typecheck = "mypy . --strict"

unittest = "python -m pytest"

check = [
  "format",
  "lint",
  "typecheck",
]

test = [
  "unittest",
  "integrationtest"
]

check_ro = [
  "format_ro",
  "lint_ro",
  "typecheck",
]

fullcheck = [
  "check",
  "test"
]

fullcheck_ro = [
  "check_ro",
  "test"
]
  

[tool.ruff]
line-length = 100
select = [ "ALL" ]
fix = true
exclude = ['stubs']
ignore = [ 
  "COM812",
  "ISC001",
  "D203",
  "D213",
  "D104",  
  "D107",  
  "ANN101",
  "ANN401",
  "FIX002",
  "TD004",
  "TD002",
  "TD003",
  "FBT001",
  "ERA001",
  "PGH003",
  "RET504",
  "D301"
]

[tool.ruff.lint.per-file-ignores]
  "tests/*" = [ "S101" ]

[tool.ruff.lint.flake8-annotations]
# https://docs.astral.sh/ruff/rules/missing-return-type-special-method/
mypy-init-return = true 
  # "D203", "D212", "S101", "EXE002", "D1", "B008" ]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
